GET http://localhost:3001/posts/638240a2d3a0f0a67ec3e9d1

###

GET http://localhost:3001/posts

###

POST http://localhost:3001/register
Content-Type: application/json

{
    "username":"bbbbbbb",
    "email":"bbbbb@abc",
    "password":"bbbbbbb"
}

###

POST http://localhost:3001/login
Content-Type: application/json

{
    "email":"ruppuus@abc",
    "password":"ruppaliiis"
}

###

GET http://localhost:3001/getme

###

POST http://localhost:3001/posts
Content-Type: application/json

{
    "title":"Focus",
    "author":"Nimisha",
    "content":"Deep Work HyperFocus",
    "tags":["teepu", "teepu", "teep"]
}

###

DELETE http://localhost:3001/posts/638240a2d3a0f0a67ec3e9d1
