GET http://localhost:3001/posts/638240a2d3a0f0a67ec3e9d1

###

GET http://localhost:3001/posts

###

POST http://localhost:3001/register
Content-Type: application/json

{
    "username":"piyushtiwari",
    "email":"piyushtiwari@abc",
    "password":"mai chutiya hu"
}

###

POST http://localhost:3001/login
Content-Type: application/json

{
    "email":"bbbbb@abc",
    "password":"bbbbbbb"
}

###

GET http://localhost:3001/getme

###

POST http://localhost:3001/posts
Content-Type: application/json

{
    "title":" React Tutorial",
    "author":"Rishika",
    "content":"React part 1 tutorial",
    "tags":["teepu", "teepu", "teep"]
}

###

DELETE http://localhost:3001/posts/638240a2d3a0f0a67ec3e9d1
